=== mnchapel/packy/resources/json/session_save_schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://example.com/schemas/session_save.json",
  "description": "Schema for defining archive session configurations and file archiving tasks",
  "type": "object",
  "properties": {
    "$schema": {
      "description": "The schema against which to verify this document",
      "type": "string",
      "format": "uri-reference"
    },
    "$id": {
      "description": "A unique identifier for the schema resource",
      "type": "string",
      "format": "uri-reference"
    },
    "version": {
      "description": "The software version compatible with this data structure",
      "type": "string",
      "minLength": 1
    },
    "session_name": {
      "description": "The descriptive name of the session",
      "type": "string",
      "minLength": 1
    },
    "dirname": {
      "description": "Absolute path to the directory where archives are generated",
      "type": "string",
      "pattern": "^([a-zA-Z]:[\\\\/]|/)[^<>:\"|?*]+$"
    },
    "tasks": {
      "description": "A list of archive batch creation tasks",
      "type": "array",
      "items": {
        "description": "Configuration parameters for a specific task.",
        "type": "object",
        "properties": {
          "id": {
            "description": "The unique task identifier",
            "type": "integer",
            "minimum": 0
          },
          "checked": {
            "description": "Task selection state between Unchecked (value 0), Checked (value 1), or Indeterminate (value 2)",
            "type": "integer",
            "enum": [0, 1, 2]
          },
          "files_model": {
            "description": "Definition of files to be included in the archive",
            "type": "object",
            "properties": {
              "root_path": {
                "description": "Absolute path to the source directory containing files to be archived",
                "pattern": "^([a-zA-Z]:[\\\\/]|/)[^<>:\"|?*]+$"
              },
              "check": {
                "description": "A map of absolute file paths to their inclusion status",
                "type": "object",
                "patternProperties": {
                  "^([a-zA-Z]:[\\\\/]|/)[^<>:\"|?*]+(?:\\.[a-zA-Z0-9]+)?$": {
                    "description": "The selection status of the file between Unchecked (value 0), Checked (value 1), or Indeterminate (value 2)",
                    "type": "integer",
                    "enum": [0, 1, 2]
                  }
                },
                "additionalProperties": false
              }
            },
            "required": [
              "root_path",
              "check"
            ],
            "additionalProperties": false
          },
          "packer_data": {
            "description": "Configuration settings for the archiving tool",
            "type": "object",
            "properties": {
              "type": {
                "description": "The numeric ID of the archiving tool to be used",
                "type": "integer",
                "minimum": 0
              },
              "compression_method": {
                "description": "The numeric ID of the compression algorithm",
                "type": "integer",
                "minimum": 0
              },
              "compression_level": {
                "description": "The compression intensity level (0 for no compression)",
                "type": "integer",
                "minimum": 0
              }
            },
            "required": [
              "type",
              "compression_method",
              "compression_level"
            ],
            "additionalProperties": false
          },
          "dst_raw_basename": {
            "description": "The base filename of the archive in the destination directory (excluding extension)",
            "type": "string",
            "minLength": 1
          },
          "dst_folder": {
            "description": "Absolute path to the destination directory for the archive",
            "pattern": "^([a-zA-Z]:[\\\\/]|/)[^<>:\"|?*]+$"
          }
        },
        "required": [
          "id",
          "checked",
          "files_model",
          "packer_data",
          "dst_raw_basename",
          "dst_folder"
        ],
        "additionalProperties": false
      }
    }
  },
    "required": [
    "version",
    "session_name",
    "dirname",
    "tasks"
  ],
  "additionalProperties": false
}

=== mnchapel/packy/resources/json/session_save_sample.json
{
  "version": "0.9.0.0",
  "session_name": "session_save.json",
  "dirname": "C:/Users/garnj/2_Projets/2.3.13.600_Packy/P4_Realisation/dev/tests/data/input_session",
  "tasks": [
    {
      "id": 6,
      "checked": 2,
      "files_model": {
        "root_path": "C:/Users/garnj/2_Projets/2.3.13.600_Packy/P4_Realisation/dev/tests/data/input_file_system/software_01",
        "check": {
          "C:/Users/garnj/2_Projets/2.3.13.600_Packy/P4_Realisation/dev/tests/data/input_file_system/software_01/folder_30": 2,
          "C:/Users/garnj/2_Projets/2.3.13.600_Packy/P4_Realisation/dev/tests/data/input_file_system/software_01/folder_10": 2,
          "C:/Users/garnj/2_Projets/2.3.13.600_Packy/P4_Realisation/dev/tests/data/input_file_system/software_01/folder_10/file_01.txt": 2,
          "C:/Users/garnj/2_Projets/2.3.13.600_Packy/P4_Realisation/dev/tests/data/input_file_system/software_01/folder_10/file_02.txt": 2,
          "C:/Users/garnj/2_Projets/2.3.13.600_Packy/P4_Realisation/dev/tests/data/input_file_system/software_01/folder_10/file_03.txt": 2,
          "C:/Users/garnj/2_Projets/2.3.13.600_Packy/P4_Realisation/dev/tests/data/input_file_system/software_01/folder_10/folder_100": 2,
          "C:/Users/garnj/2_Projets/2.3.13.600_Packy/P4_Realisation/dev/tests/data/input_file_system/software_01/folder_10/folder_200": 2,
          "C:/Users/garnj/2_Projets/2.3.13.600_Packy/P4_Realisation/dev/tests/data/input_file_system/software_01/folder_10/folder_300": 2,
          "C:/Users/garnj/2_Projets/2.3.13.600_Packy/P4_Realisation/dev/tests/data/input_file_system/software_01/folder_20": 2,
          "C:/Users/garnj/2_Projets/2.3.13.600_Packy/P4_Realisation/dev/tests/data/input_file_system/software_01/folder_20/file_01.txt": 2,
          "C:/Users/garnj/2_Projets/2.3.13.600_Packy/P4_Realisation/dev/tests/data/input_file_system/software_01/folder_20/file_02.txt": 2,
          "C:/Users/garnj/2_Projets/2.3.13.600_Packy/P4_Realisation/dev/tests/data/input_file_system/software_01/folder_20/file_03.txt": 2,
          "C:/Users/garnj/2_Projets/2.3.13.600_Packy/P4_Realisation/dev/tests/data/input_file_system/software_01/file_01.txt": 2,
          "C:/Users/garnj/2_Projets/2.3.13.600_Packy/P4_Realisation/dev/tests/data/input_file_system/software_01/file_02.txt": 2,
          "C:/Users/garnj/2_Projets/2.3.13.600_Packy/P4_Realisation/dev/tests/data/input_file_system/software_01/file_03.txt": 2,
          "C:/Users/garnj/2_Projets/2.3.13.600_Packy/P4_Realisation/dev/tests/data/input_file_system/software_01/file_04.txt": 2,
          "C:/Users/garnj/2_Projets/2.3.13.600_Packy/P4_Realisation/dev/tests/data/input_file_system/software_01/file_05.txt": 2,
          "C:/Users/garnj/2_Projets/2.3.13.600_Packy/P4_Realisation/dev/tests/data/input_file_system/software_01/file_07.txt": 2,
          "C:/Users/garnj/2_Projets/2.3.13.600_Packy/P4_Realisation/dev/tests/data/input_file_system/software_01/file_06.txt": 2,
          "C:/Users/garnj/2_Projets/2.3.13.600_Packy/P4_Realisation/dev/tests/data/input_file_system/software_01/folder_10/folder_100/file_01.txt": 2,
          "C:/Users/garnj/2_Projets/2.3.13.600_Packy/P4_Realisation/dev/tests/data/input_file_system/software_01/folder_10/folder_100/file_02.txt": 2,
          "C:/Users/garnj/2_Projets/2.3.13.600_Packy/P4_Realisation/dev/tests/data/input_file_system/software_01/folder_10/folder_100/file_03.txt": 2,
          "C:/Users/garnj/2_Projets/2.3.13.600_Packy/P4_Realisation/dev/tests/data/input_file_system/software_01/folder_10/folder_200/file_01.txt": 2,
          "C:/Users/garnj/2_Projets/2.3.13.600_Packy/P4_Realisation/dev/tests/data/input_file_system/software_01/folder_10/folder_200/file_02.txt": 2,
          "C:/Users/garnj/2_Projets/2.3.13.600_Packy/P4_Realisation/dev/tests/data/input_file_system/software_01/folder_10/folder_200/file_03.txt": 2
        }
      },
      "packer_data": {
        "type": 0,
        "compression_method": 0,
        "compression_level": 0
      },
      "dst_raw_basename": "software_01",
      "dst_folder": "C:/Users/garnj/2_Projets/2.3.13.600_Packy/P4_Realisation/dev/tests/data/output_archives"
    },
    {
      "id": 7,
      "checked": 2,
      "files_model": {
        "root_path": "C:/Users/garnj/2_Projets/2.3.13.600_Packy/P4_Realisation/dev/tests/data/input_file_system/software_02",
        "check": {
          "C:/Users/garnj/2_Projets/2.3.13.600_Packy/P4_Realisation/dev/tests/data/input_file_system/software_02/folder_30": 2,
          "C:/Users/garnj/2_Projets/2.3.13.600_Packy/P4_Realisation/dev/tests/data/input_file_system/software_02/folder_20": 2,
          "C:/Users/garnj/2_Projets/2.3.13.600_Packy/P4_Realisation/dev/tests/data/input_file_system/software_02/folder_20/file_01.txt": 2,
          "C:/Users/garnj/2_Projets/2.3.13.600_Packy/P4_Realisation/dev/tests/data/input_file_system/software_02/folder_20/file_02.txt": 2,
          "C:/Users/garnj/2_Projets/2.3.13.600_Packy/P4_Realisation/dev/tests/data/input_file_system/software_02/folder_20/file_03.txt": 2,
          "C:/Users/garnj/2_Projets/2.3.13.600_Packy/P4_Realisation/dev/tests/data/input_file_system/software_02/folder_10": 1,
          "C:/Users/garnj/2_Projets/2.3.13.600_Packy/P4_Realisation/dev/tests/data/input_file_system/software_02/folder_10/file_01.txt": 0,
          "C:/Users/garnj/2_Projets/2.3.13.600_Packy/P4_Realisation/dev/tests/data/input_file_system/software_02/folder_10/file_02.txt": 0,
          "C:/Users/garnj/2_Projets/2.3.13.600_Packy/P4_Realisation/dev/tests/data/input_file_system/software_02/folder_10/file_03.txt": 0,
          "C:/Users/garnj/2_Projets/2.3.13.600_Packy/P4_Realisation/dev/tests/data/input_file_system/software_02/folder_10/folder_100": 2,
          "C:/Users/garnj/2_Projets/2.3.13.600_Packy/P4_Realisation/dev/tests/data/input_file_system/software_02/folder_10/folder_200": 0,
          "C:/Users/garnj/2_Projets/2.3.13.600_Packy/P4_Realisation/dev/tests/data/input_file_system/software_02/folder_10/folder_300": 0,
          "C:/Users/garnj/2_Projets/2.3.13.600_Packy/P4_Realisation/dev/tests/data/input_file_system/software_02/folder_10/folder_100/file_01.txt": 2,
          "C:/Users/garnj/2_Projets/2.3.13.600_Packy/P4_Realisation/dev/tests/data/input_file_system/software_02/folder_10/folder_100/file_02.txt": 2,
          "C:/Users/garnj/2_Projets/2.3.13.600_Packy/P4_Realisation/dev/tests/data/input_file_system/software_02/folder_10/folder_100/file_03.txt": 2,
          "C:/Users/garnj/2_Projets/2.3.13.600_Packy/P4_Realisation/dev/tests/data/input_file_system/software_02/file_01.txt": 2,
          "C:/Users/garnj/2_Projets/2.3.13.600_Packy/P4_Realisation/dev/tests/data/input_file_system/software_02/file_02.txt": 2,
          "C:/Users/garnj/2_Projets/2.3.13.600_Packy/P4_Realisation/dev/tests/data/input_file_system/software_02/file_03.txt": 2,
          "C:/Users/garnj/2_Projets/2.3.13.600_Packy/P4_Realisation/dev/tests/data/input_file_system/software_02/file_04.txt": 2,
          "C:/Users/garnj/2_Projets/2.3.13.600_Packy/P4_Realisation/dev/tests/data/input_file_system/software_02/file_05.txt": 2,
          "C:/Users/garnj/2_Projets/2.3.13.600_Packy/P4_Realisation/dev/tests/data/input_file_system/software_02/file_06.txt": 2,
          "C:/Users/garnj/2_Projets/2.3.13.600_Packy/P4_Realisation/dev/tests/data/input_file_system/software_02/file_07.txt": 2
        }
      },
      "packer_data": {
        "type": 0,
        "compression_method": 0,
        "compression_level": 0
      },
      "dst_raw_basename": "software_02",
      "dst_folder": "C:/Users/garnj/2_Projets/2.3.13.600_Packy/P4_Realisation/dev/tests/data/output_archives"
    },
    {
      "id": 8,
      "checked": 2,
      "files_model": {
        "root_path": "C:/Users/garnj/2_Projets/2.3.13.600_Packy/P4_Realisation/dev/tests/data/input_file_system/software_03",
        "check": {}
      },
      "packer_data": {
        "type": 0,
        "compression_method": 0,
        "compression_level": 0
      },
      "dst_raw_basename": "software_03",
      "dst_folder": "C:/Users/garnj/2_Projets/2.3.13.600_Packy/P4_Realisation/dev/tests/data/output_archives"
    },
    {
      "id": 9,
      "checked": 2,
      "files_model": {
        "root_path": "C:/Users/garnj/2_Projets/2.3.13.600_Packy/P4_Realisation/dev/tests/data/input_file_system/software_04",
        "check": {}
      },
      "packer_data": {
        "type": 0,
        "compression_method": 0,
        "compression_level": 0
      },
      "dst_raw_basename": "software_04",
      "dst_folder": "C:/Users/garnj/2_Projets/2.3.13.600_Packy/P4_Realisation/dev/tests/data/output_archives"
    },
    {
      "id": 10,
      "checked": 2,
      "files_model": {
        "root_path": "C:/Users/garnj/2_Projets/2.3.13.600_Packy/P4_Realisation/dev/tests/data/input_file_system/software_05",
        "check": {}
      },
      "packer_data": {
        "type": 0,
        "compression_method": 0,
        "compression_level": 0
      },
      "dst_raw_basename": "software_05",
      "dst_folder": "C:/Users/garnj/2_Projets/2.3.13.600_Packy/P4_Realisation/dev/tests/data/output_archives"
    },
    {
      "id": 11,
      "checked": 2,
      "files_model": {
        "root_path": "C:/Users/garnj/2_Projets/2.3.13.600_Packy/P4_Realisation/dev/tests/data/input_file_system/software_without_files",
        "check": {}
      },
      "packer_data": {
        "type": 0,
        "compression_method": 0,
        "compression_level": 0
      },
      "dst_raw_basename": "software_06",
      "dst_folder": "C:/Users/garnj/2_Projets/2.3.13.600_Packy/P4_Realisation/dev/tests/data/output_archives"
    }
  ]
}
